language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: integration-dev@thomascookonline.com
  api_key:
    secure: BTaQMRhRFJR9M3BOMAzRrTTw72HuAqv455i+eD6dGotMkI0lIP6jHWsFO/5UIZ/DElbn/148xxzvJxM5tyLZyRwel2oxtTP8Ai4YfNqiiFvtZZRI5oZKuABM4f7By4Lu1U6WQiBWU7czP89nivKe5P1aZLkriTwECvzRaBIVLxWcJBDSW7vs8opehTdClt+pOxGcU8Zw00nQg387hNA7mhzUbRHHzw6ntmOqbWXtOpeSYauV8cuK0gseMS73yR1H5vhU1y/MmZ3NFBz1UtdrYWH4T4L/hHT4WXVjrMF+Fw2nlq7NCj5H1G491gPE1Vq5LnFCVAvu4sSA0ZHx6QfsFbjcqoPktSyUyKz7yispagVlzHYBdXvimYeOdIsQK6FkOnNEL7VMn2au4GP28sVXBt6X2uTpdjQ0OV7pVzHVcfaZbe+AF8Ml2nJML9vQZHOIWVsZ2wOzu75Y8AiP7Ca+F/UzwYU8u5J61MrztTp++zwtzwkOtj7uNJvaBl3UcD+ZyHNI9QBuPt3YnQghRgY4+0gVDFcL2NuI8LD678DmZLAa9I0mH4JNOQlthbQx0fMAhJA3oBegVMiJsDbegRiQoMkNfUxW/dcVwtEKzE/DP1AAXtCEDK2mOXkE1F9vdWjX42recwrjK2g8tXsxp96ZwxmTQj1bu/cgSDuAsOxybV4=
  on:
    tags: true
    repo: tcdl/koa-actuator
    node: '7'
