language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: integration-dev@thomascookonline.com
  api_key:
    secure: dvHZLYgOzbndaSn5fwxZPMn4IK+RMDk2leEOOulNrUz4DtdB6uTdDqmLE1AHvd4ayfhrj0s9VdLGPJa9Jy6nZUO9lW0wFMhuoxrOQqPTN322canXPl2KJ2MeF677vqEl4gNqzzGx8ySl8ePzK+p3lJSFq4PyZmVrFCBa2HeuRTLhCstdYN4nZ7GbTtqDDnlub2meK1naH1+eP3OPGdfq3De0ymT6kpC148IguE/trcoAE41RA6fTEZzviKGiqnNhH+BMPfO3kjLigagK/9S/2vxake17yU78O/sYv+L7zQg7UEzbSIE2NlGkv5kHy2Jl7S1XkRrpXuuGjnQ9ZiXUXTGQE7wJ36yKbeWCevsuXz/tfe+0hOfagU7/LRpsJJrHtFV/SKmd1fmqa6uyFX613PEvmYIMnYBLQXIFHv9JlCTbtVFKXJrIWN5TKpR86VEMXHg4XCFZqJGKI0UMPUZkU89SpJtNBafasC8A3R7/gsMs+RDq2MZBsVI4sDZOwlRK9xzYpSjQVULCPhJruGXR3p4jof5zqyLZGvlyC7ypbQL8XM4owELgc5n1wBBqTjL5k0OTi/LjWm8LdMowKfVX/NfMMWOgaSlePfUqysCS1rxHQM8eYx+v14U2j2vRFEx5UOCS2cZfaD8em1sIR9NJFuW7yTTA15arZnWaafaRr1o=
  on:
    tags: true
    repo: tcdl/koa-actuator
    node: '7'
