language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: integration-dev@thomascookonline.com
  api_key:
    secure: mvsmCI4t28FFETnYKKpTUDYyxkZxzuxU3r5OGx4lKF42P/rVkdNvAPs0E9wg2Og+LAO7XyKdY7qabUPFx102pHgdwbp3iexmA7AKF1fv1RYNijCSIbWKNjK9FVyyG1GarW9F7tPDdH/jftpFGrKIKf9gssQz69rLG24Blww0OtvXFnkyrNRef2o+m72qge4RM8Kd/FqNK1ZhAdCl8giklONBjjz4SYf5XKtyouxu4bVSWO+lBPFIAg/lI/kS6yPHctdu4RFMnhKmlHUQDhGltI6lYf/dzNTDbMBIWmMKIpYuirMl+2MJlQlLlgxdolXfc03jV7z4Sg2xEZLBOb7VWK610VfG5N6hACexM9LlteTz/+4WMuU7ZbIGh4HirQTr+MwK2PKPnWJVU0YTufjoF5OdyemMjXsDJHq5XcdVgYP+/7lb4b9R6uhq4LEQJu70R5fPuybyLjDOPvW6J9e3B87k8PzWWYo9BNNdxNFmS7e4YsSNXhapHw1Iwq4XLKfoYEmcwuhutZoAv+kwL0IwR1J0aJYEwyysc22F8qBEiKCqWcYYVItqLWdQIa3f/JmeV89FGa1gzhQSWPyNo1HcfZ3eaUoexQALC9SwhQ3Dy0M01r+2BeaaqkI3WPdwOdgzAL9sjH+2fUotbNnhnEfDCU0yRiKJX0AoMW/eqETVoGI=
  on:
    tags: true
    repo: tcdl/koa-actuator
    node: '7'
